version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile.dev
      args:
        RUBY_VERSION: '2.7.2-alpine'
        BUNDLER_VERSION: '2.0.2'
    image: issue-tracker-dev:1.0.1
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - hanami_cache:/app/tmp/cache
      - bundle:/bundle
    environment:
      - HANAMI_ENV=${HANAMI_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vi
      - MALLOC_ARENA_MAX=2
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}

  hanami:
    <<: *backend
    command: bundle exec hanami server --host 0.0.0.0 --port 3000
    ports:
      - '3000:3000'
    depends_on:
      - sidekiq
      - redis

  runner:
    <<: *backend
    command: /bin/bash

  sidekiq:
    <<: *backend
    depends_on:
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml -r ./config/boot.rb --logfile log/sidekiq.log

  redis:
    image: redis:5.0.5-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  redis:
  bundle:
  hanami_cache:
